
class tryandcatch{
    public static void main(String args[]){
        int num1,num2;
                try{
                    //try block to handle code that ma
                    num1=2; 
                    num2=62/num1;
                    System.out.println("try block message");
                            }
                catch(ArithmeticException e)
                          {
                                //this block is to catch divid
                                System.out.println("Error: done");
                            }
                            System.out.println("am out of try -catch");
                            
                }
    }
   



